### ISSUE TITLE
登录时报错

### ISSUE THREAD

**Issue by whxtsangle** [zxiaosi/Vue3-FastAPI#2]
PS D:\ASIC\vue3-fastapi\backend>  d:; cd 'd:\ASIC\vue3-fastapi\backend'; & 'c:\Python311\python.exe' 'c:\Users\yahui\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '52015' '--' 'D:\ASIC\vue3-fastapi\backend\main.py' 
2024-02-17 09:05:31.803 | INFO     | core.init_db:drop_table:41 - 删除表成功!!!
2024-02-17 09:05:32.538 | INFO     | core.init_db:init_table:32 - 创建表成功!!!
2024-02-17 09:05:32.603 | INFO     | __main__:<module>:28 - 项目启动成功！！！
INFO:     Started server process [31220]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:52874 - "OPTIONS /api/user/login HTTP/1.1" 200 OK
2024-02-17 09:18:55.013 | ERROR    | register.exception:http_exception_handler:103 - 全局异常: URL:http://127.0.0.1:8000/api/user/login
Headers:Headers({'host': '127.0.0.1:8000', 'connection': 'keep-alive', 'content-length': '202', 'sec-ch-ua': '"Not_A Brand";v="8", "Chromium";v="120", "Microsoft Edge";v="120"', 'accept': 'application/json, text/plain, */*', 'content-type': 'application/json', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0', 'sec-ch-ua-platform': '"Windows"', 'origin': 'http://127.0.0.1:5173', 'sec-fetch-site': 'same-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'referer': 'http://127.0.0.1:5173/', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6'})
Traceback (most recent call last):
  File "C:\Users\yahui\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\yahui\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\yahui\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\yahui\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\yahui\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "c:\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "C:\Users\yahui\AppData\Roaming\Python\Python311\site-packages\fastapi\concurrency.py", line 36, in contextmanager_in_threadpool
    raise e
TypeError: 'NoneType' object is not subscriptable

你好请教一下，我现在点击登录时后台报错，根据断点定位到报错是/utils/handle_cookie.py里的def set_cookie方法里创建LocalUser(**_user, pk=session)报错，请问可能是什么原因

**Comment by zxiaosi** [comment]
可能需要配置一下 [RedisJSON](https://gitee.com/link?target=https%3A%2F%2Fredis.io%2Fdocs%2Fstack%2Fjson%2F)
我写的有这个配置的文章 [https://zxiaosi.com/archives/26a72a9d.html](https://gitee.com/link?target=https%3A%2F%2Fzxiaosi.com%2Farchives%2F26a72a9d.html) :grin:

Gitee上有相同的 [Issues](https://gitee.com/zxiaosi/vue3-fastapi/issues/I79IML#note_24462097_link)
